name: C++ CI Build and Run Examples (GCC, Conan 1.x, Release)

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Conan 1.x
      run: |
        pip install conan==1.59.0
        conan --version

    - name: Create build directory
      run: mkdir build

    - name: Run Conan install for Release configuration
      working-directory: build
      run: |
        echo "Running Conan install for Release configuration..."
        conan install .. --build=missing -s build_type=Release -g cmake -s compiler.version=12

    - name: Configure CMake
      working-directory: build
      run: cmake .. -DCMAKE_BUILD_TYPE=Release -DCONAN_DISABLE_CHECK_COMPILER=ON -DBUILD_TESTS=ON

    - name: Build project
      working-directory: build
      run: cmake --build .

    - name: Run func_invoke_cpp17
      working-directory: build/bin/Release
      run: ./func_invoke_cpp17

    - name: Run func_invoke_cpp20
      working-directory: build/bin/Release
      run: ./func_invoke_cpp20
